language: python

python:
    - "2.7"

cache:
    directories:
        - $HOME/.cache

# sudo: false
sudo: required

dist: trusty

compiler:
    - gcc

addons:
    apt:
        packages:
            # Pillow dependencies (see
            # https://pillow.readthedocs.org/en/latest/installation.html)
            - libtiff5-dev
            - libjpeg8-dev
            - zlib1g-dev
            - libfreetype6-dev
            - liblcms2-dev
            - libwebp-dev
            - tcl8.6-dev
            - tk8.6-dev
            - python-tk
            # vips
            - libvips-tools

before_install:
    - main_path=$PWD
    - build_path=$PWD/build
    - mkdir -p $build_path

    - girder_path=$build_path/girder
    - rm -fr $girder_path
    - git clone https://github.com/girder/girder.git $girder_path && git -C $girder_path checkout 114b5dda576bc0611617a92f88942f3a55dabe7d
    - ln -sf $main_path $girder_path/plugins/
    - ls -l $girder_path/plugins

    - romanesco_path=$girder_path/plugins/romanesco
    - git clone https://github.com/Kitware/romanesco.git $romanesco_path && git -C $romanesco_path checkout 14a38e1e918d79446e59d4eb0d9e46571e2b8458
    - cp $PWD/plugin_tests/data/romanesco.cfg $romanesco_path/romanesco/worker.local.cfg
    - pip install -U -r $romanesco_path/requirements.txt -r $romanesco_path/romanesco/plugins/girder_io/requirements.txt

    - export MONGO_VERSION=2.6.11
    - export PY_COVG="ON"
    - CACHE=$HOME/.cache source $girder_path/scripts/install_mongo.sh
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version

    - CACHE=$HOME/.cache CMAKE_VERSION=3.1.0 CMAKE_SHORT_VERSION=3.1 source $girder_path/scripts/install_cmake.sh
    - cmake --version

    - npm install -g npm
    - npm --version

    - pip install -U pip virtualenv

install:
    - cd $girder_path
    - pip install -U -r requirements.txt -r requirements-dev.txt -r $main_path/requirements.txt -e .
    - npm install

script:
    - cd $romanesco_path
    - python -m romanesco &
    - mkdir -p $build_path/girder_testing_build
    - cd $build_path/girder_testing_build
    - cmake -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} $girder_path
    - make
    - JASMINE_TIMEOUT=15000 ctest -VV -R large_image
