language: python

python:
    - "2.7"

cache:
    directories:
        - $HOME/.cache

# sudo: false
sudo: required

dist: trusty

compiler:
    - gcc

addons:
    apt:
        packages:
            # Pillow dependencies (see
            # https://pillow.readthedocs.org/en/latest/installation.html)
            - libtiff5-dev
            - libjpeg8-dev
            - zlib1g-dev
            - libfreetype6-dev
            - liblcms2-dev
            - libwebp-dev
            - tcl8.6-dev
            - tk8.6-dev
            - python-tk
            # vips
            - libvips-tools
            # openslide
            - openslide-tools

before_install:
    - main_path=$PWD
    - build_path=$PWD/build
    - mkdir -p $build_path

    # There is an issue with the OpenJPEG library included with Ubuntu 14.04,
    # so install it from source.
    - wget http://downloads.sourceforge.net/project/openjpeg.mirror/2.0.1/openjpeg-2.0.1.tar.gz
    - tar zxf openjpeg-2.0.1.tar.gz
    - cd openjpeg-2.0.1
    - cmake .
    - sudo make install
    - cd $main_path

    - girder_path=$build_path/girder
    - rm -fr $girder_path
    - git clone https://github.com/girder/girder.git $girder_path && git -C $girder_path checkout 18796e2353b6f41da73d235c391ac8f36fdc2cd6
    - ln -sf $main_path $girder_path/plugins/
    - ls -l $girder_path/plugins

    - girder_worker_path=$girder_path/plugins/girder_worker
    - git clone https://github.com/girder/girder_worker.git $girder_worker_path && git -C $girder_worker_path checkout 4429c6e98b2b11d47edb43390571551ab2d36749
    - cp $PWD/plugin_tests/data/girder_worker.cfg $girder_worker_path/girder_worker/worker.local.cfg
    - pip install numpy==1.10.4  # needed because libtiff doesn't install correctly without it.  This ensures we have the same version for libtiff as for the project.
    - pip install -U -r $girder_worker_path/requirements.txt -r $girder_worker_path/girder_worker/plugins/girder_io/requirements.txt

    - export MONGO_VERSION=2.6.11
    - export PY_COVG="ON"
    - CACHE=$HOME/.cache source $girder_path/scripts/install_mongo.sh
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version

    - CACHE=$HOME/.cache CMAKE_VERSION=3.1.0 CMAKE_SHORT_VERSION=3.1 source $girder_path/scripts/install_cmake.sh
    - cmake --version

    - npm install -g npm
    - npm --version

    - pip install -U pip virtualenv

install:
    - cd $girder_path
    - pip install -U -r requirements.txt -r requirements-dev.txt -r $main_path/requirements.txt -e .
    - npm install

script:
    - cd $girder_worker_path
    - python -m girder_worker &
    - mkdir -p $build_path/girder_testing_build
    - cd $build_path/girder_testing_build
    - cmake -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} $girder_path
    - make
    - JASMINE_TIMEOUT=15000 ctest -VV -R large_image
