version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: zachmullen/tox-and-node
      - image: memcached
      - image: circleci/mongo:4.0-ram
      - image: rabbitmq
    steps:
      - checkout
      - run:
          name: Preinstall phantomjs to work around an npm permission issue
          command: npm install -g phantomjs-prebuilt --unsafe-perm
      - run:
          name: Run tests via tox
          command: tox | cat
      - run:
          name: Install Codecov client
          command: pip install codecov
      - run:
          name: Upload coverage
          command: codecov --disable search pycov gcov --root project --file build/test/coverage/py_coverage.xml build/test/coverage/cobertura-coverage.xml
