---
- name: Converge
  hosts: all
  vars:
    - large_image_include_vips: true
    - large_image_virtualenv: "~/.virtualenvs/large_image"

  pre_tasks:

    - name: Install python, pip and virtualenv
      apt:
        name:
          - python-dev
          - python-pip
          - python-virtualenv

    - name: Create virtuelenv for large_image
      command: virtualenv "{{ large_image_virtualenv }}"
      args:
        creates: "{{ large_image_virtualenv }}"
        removes: "{{ large_image_virtualenv }}"

  roles:
    - role: large_image
