---
- name: Install Girder
  hosts: all
  pre_tasks:
    - name: Create root directory
      file:
        path: "{{ root_dir }}"
        group: "{{ girder_user|default(ansible_user_id) }}"
        owner: "{{ girder_user|default(ansible_user_id) }}"
        state: directory
        mode: 0755
      become: yes
      become_user: root

  roles:

    - role: girder.girder
      girder_version: "2.x-maintenance"
      # We build the girder web assets in a later playbook
      girder_web: no
      become: true
      become_user: "{{ girder_user | default(ansible_user_id) }}"

  post_tasks:
    - name: Ensures service override dir exists
      file:
        path: /etc/systemd/system/girder.service.d/
        state: directory
      when: girder_daemonize
      become: yes
      become_user: root

    - name: Install Girder Service override
      template:
        src: girder.service.override
        dest: /etc/systemd/system/girder.service.d/override.conf
      when: girder_daemonize
      become: yes
      become_user: root

    - name: Install libtiff
      apt:
        name: libtiff5-dev
      become: yes
      become_user: root


- name: Install Mapnik dependencies
  hosts: memcached
  become: yes
  become_user: root
  tasks:
    - name: Install memcached
      apt:
        name: memcached

- name: Install Mapnik dependencies
  hosts: mapnik
  become: yes
  become_user: root
  tasks:
    - name: Install system packages
      apt:
        name:
          - libgdal-dev
          - gdal-bin
          - libmapnik-dev
          - python-mapnik

    - name: Install GDAL 1 python package
      pip:
        name: gdal==1.10.0
        chdir: "{{ large_image_path }}"

  environment:
    CPLUS_INCLUDE_PATH: /usr/include/gdal
    C_INCLUDE_PATH: /usr/include/gdal


- name: Install Openslide dependencies
  hosts: openslide
  pre_tasks:
    - name: Remove Stock libtiff
      apt:
        name: libtiff5-dev
        state: absent
      become: yes
      become_user: root

    - name: Remove Stock libtiff
      apt:
        autoremove: yes
      become: yes
      become_user: root

  roles:
    - role: DigitalSlideArchive.vips


- name: Install Large Image
  hosts: all
  roles:
    - role: large_image
      # Note: Take the groups this host is in, do a set intersection
      # with the list of valid extras_require and join them as a comma
      # seperated list.
      large_image_extras_require: "{{ group_names | intersect(['memcached', 'openslide', 'mapnik' ]) }}"
    - role: npm

  post_tasks:
    - name: Rebuild Girder web
      command: "girder-install web --dev --plugins large_image,worker,jobs"
