- name: Provision Large Image
  hosts: docker
  tasks:
    - name: Install girder-client
      pip:
        name: girder-client
      become: yes

    - name: Create admin user
      girder:
        port: 8080
        user:
          firstName: "Girder"
          lastName: "Administrator"
          login: "girder"
          password: "girder"
          email: "girder@girder.girder"
          admin: yes
        state: present

    - name: Setup filesystem assetstore
      girder:
        port: 8080
        username: "girder"
        password: "girder"
        assetstore:
          name: "Primary assetstore"
          type: "filesystem"
          root: "{{ ansible_user_dir }}/assetstore"
          current: true
        state: present
      register: assetstore

    - name: Enable Large Image plugin
      girder:
        port: 8080
        username: "girder"
        password: "girder"
        plugins:
          - large_image
        state: present

    - name: Rebuild Girder web
      command: "girder-install web --dev --all-plugins"

    - name: Restart the server
      girder:
        port: 8080
        username: "girder"
        password: "girder"
        put:
          path: "system/restart"

    - name: Wait for Girder to be available
      wait_for:
        port: 8080
