- name: Tweak Girder server configurations
  ini_file:
    dest: "{{ girder_path }}/girder/conf/girder.local.cfg"
    backup: true
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "global", option: "server.socket_host", value: '"0.0.0.0"' }

- name: Install Girder-Client
  pip:
    name: "girder-client"
    state: present
  become: true
  become_user: root

- name: Wait for Girder to be available
  wait_for:
    port: 8080

- name: Create Girder User
  girder:
    port: 8080
    user:
      firstName: "girder"
      lastName: "girder"
      login: "admin"
      password: "letmein"
      email: "girder@girder.girder"
      admin: true
      state: present

- name: Create filesystem assetstore
  girder:
    username: "admin"
    password: "letmein"
    assetstore:
      name: "Filesystem Assetstore"
      type: "filesystem"
      root: "/tmp/assetstore/"
      current: true
    state: present

- name: Enable plugins
  girder:
    username: "admin"
    password: "letmein"
    port: 8080
    plugins:
      - large_image
    state: present

- name: Restart Girder
  service:
    name: girder
    state: restarted
  become: true
  become_user: root

- name: Wait for Girder to be available
  wait_for:
    port: 8080

- name: Set Worker API Url
  girder:
    port: 8080
    username: "admin"
    password: "letmein"
    setting:
      key: "worker.api_url"
      value: "http://localhost:8080/api/v1"

- name: Rebuild Client
  girder:
    username: "admin"
    password: "letmein"
    post:
      path: "system/web_build"
