---
- name: Check for supported operating systems
  fail:
    msg: "large_image role only supports ubuntu 16.04 and 18.04"
  when: (ansible_distribution_version != "16.04") and
        (ansible_distribution_version != "18.04")

- name: Check if the virtualenv is specified
  fail:
    msg: "large_image role requires large_image_virtualenv variable"
  when: large_image_virtualenv is not defined

- name: Install numpy
  pip:
    name: numpy
    virtualenv: "{{ large_image_virtualenv }}"

- name: Install git
  apt:
    name: git
  become: true
  become_user: root

- include_tasks: pil.yml
  when: '"pil" in large_image_tile_sources'

- include_tasks: tiff.yml
  when: '"tiff" in large_image_tile_sources'

- include_tasks: svs.yml
  when: '"svs" in large_image_tile_sources'

- include_tasks: mapnik.yml
  when: '"mapnik" in large_image_tile_sources'

- name: Install large_image
  pip:
    name: git+https://github.com/girder/large_image
    virtualenv: "{{ large_image_virtualenv }}"
