---
- name: Check for supported operating systems
  fail:
    msg: "large_image role only supports ubuntu 16.04 and 18.04"
  when: (ansible_distribution_version != "16.04") and
        (ansible_distribution_version != "18.04")

- name: Check if the virtualenv is specified
  fail:
    msg: "large_image role requires large_image_virtualenv variable"
  when: large_image_virtualenv is not defined

- name: Install numpy
  pip:
    name: numpy
    virtualenv: "{{ large_image_virtualenv }}"

- name: Install git
  apt:
    name: git
  become: true
  become_user: root

- name: Import tile sources
  include_tasks: "{{ tile_source }}.yml"
  when: tile_source in large_image_tile_sources
  loop:
    - pil
    - tiff
    - svs
    - mapnik
  loop_control:
    loop_var: tile_source

- import_tasks: vips.yml
  when: large_image_include_vips

- name: Set large image path as a fact
  set_fact:
    large_image_path: "{{ large_image_path }}"

- name: Clone large image repository
  git:
    repo: "{{ large_image_url }}"
    version: "{{ large_image_version }}"
    dest: "{{ large_image_path }}"

# When pip packages are installed from a path, pip module
# does not do idempotency checks. That is why we have
# check the path with stat module to make the task idempotent
- name: Check if large_image package exists in virtualenv
  stat:
    path: "{{ large_image_virtualenv }}/large_image"
  register: stat_results

- name: Install large_image
  pip:
    name: "{{ large_image_path }}"
    virtualenv: "{{ large_image_virtualenv }}"
  changed_when: not stat_results.stat.exists
