version: "3"
services:
  mongodb:
    image: "mongo:3.4"
    ports:
      - "27017"
  broker:
    image: "rabbitmq:3"
  large_image:
    volumes:
      - ../../:/large_image
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - "mongodb:mongodb"
      - "broker:broker"
